### PR TITLE
Fixed #17

### LINKED ISSUE #17: Bug: driver fails to mount remoted moutned volume
Condition to reproduce issue:
- In swarm mode
- volume mounted on remote node and not in use by node or container.
- remote node silently did not unmount the volume.
- try mounting the volume locally node.
- plugin fails to mount with "failed to attach volume.. already attached"

Cause:
- plugin tries to attach the volume while it is already associated to another node

Fix:
- submit detach request if volume already associated with another node.
- Kernel unmounts volume when detach request is made.

### PR DESCRIPTION
**Pull request by ricardorg79**
- Send detach request when volume associated with a remote node.

### CODE REVIEW

**Comment by davazp** [comment]
Hey @ricardorg79 

Do you plan to merge this as it is?

If I understand correctly, it will detach it from another linode.  Even if that volume is actually used by other container, right?  Is this safe? could it cause some corruption if it is being used by, for example, a database?

What if we send a detach request when a container is stopped? That means that to use the volume in another container, you would stop the old one  and start a new one , possibly in another docker swarm node.

Thanks,
David.

**Comment by ricardorg79** [comment]
Hi @davazp,

You  are correct in your assumption that it will try to detach the volume from another Linode in the case you explain.   This PR is meant to  fix a very specific case:
- Node A is trying to mount the volume
- Node B has the volume attached (maybe mounted) but no container is using it.
- Node A sees volume as already attached, assumes it is attached to itself and  tries to mount it.
to fix this we need to issue an Detach and Attach to Node A.

The case you are talking about is a little trickier to handle without keeping state.  Unfortunately volumes can not be mounted on multiple Linodes at the same time.   There are a couple of ways we could handle this:
- We could leverage Docker and Linode API to try and figure out if a volume is actually in use and fail fast.
- Another way would be to add a suffix to volume names with a container number.  This way we have to actually match the number of volumes.

I haven't have the time lately to work on this, but I would take any suggestions! 

I just haven't have the time to work on that.

**Comment by davazp** [comment]
> * Node A sees volume as already attached, assumes it is attached to itself and  tries to mount it.
  to fix this we need to issue an Detach and Attach to Node A.

I'm not sure if I understand this. Why would it assume it is attached to itself?

```
// If Volume not already attached to this Linode, then attach		// if volume not attached, attach to this linode
	if linVol.LinodeID == nil || *linVol.LinodeID != driver.instanceID 
```

it seems it knows about the instance it is attached to, so if it is mounted, we could check if it is different and give an error.


On the other hand, about my specific proposal:
> What if we send a detach request when a container is stopped?

Couldn't this work without state? If a volume is attached to a node without containers using it, it would block it, yes. But maybe we can prevent this in normal cases by detaching the volume when containers are stopped.

With that approach, it would work like:

- Volume start detached it.
- Node 1 starts a container with the volume, it gets attached and mounted.
- Node 2 tries to start a container, but fails because the volume is attached.
- Node 1 stops the container, the volume is detached.
- Node 2 tries to start a container, this time it works because the container is not attached.

**Comment by ricardorg79** [comment]
I'm glad you are looking at this with fresh eyes.   I don't remember if what you are talking about was the reason this wasn't merged.  it was some time ago since I last looked at this.

With that approach, it would work like:

* Volume start detached it.
* Node 1 starts a container with the volume, it gets attached and mounted.
* Node 2 tries to start a container, but fails because the volume is attached.
* Node 1 stops the container, the volume is detached.
* Node 2 tries to start a container, this time it works because the container is not attached.

**Comment by ricardorg79** [comment]
I'm glad you are looking at this with fresh eyes.   I don't remember if what you are talking about was the reason this wasn't merged.  it was some time ago since I last looked at this.

> With that approach, it would work like:
> 
> * Volume start detached it.
> * Node 1 starts a container with the volume, it gets attached and mounted.
> * Node 2 tries to start a container, but fails because the volume is attached.
> * Node 1 stops the container, the volume is detached.
> * Node 2 tries to start a container, this time it works because the container is not attached.
That makes a lot of sense. we can:
- Issue a `Detach` when `Unmount` is called. (when the container exits)
- Use Docker API to find if a volume is in use by a container.
- Fail Attach/Mount if volume is already in use by a container.
- If Volume not in use, I would still like to issue a Detach if another Linode has it attached and Volume not in use ( a just in case scenario)

I'm unsure about the [Docker API part](https://docs.docker.com/engine/api/v1.39/#operation/VolumeInspect).  I can't find where it tells you that a volume is in use or not.  I'll do more digging.

**Comment by displague** [comment]
@davazp @ricardorg79 
I've merged this along with changes to attempt to detect if the volume is in use by an active container.  I believe this should work in a swarm setting.  Along with this there have been many README updates.

Let me know how these changes work in your setting.  The `latest` docker image has the changes.

```
docker plugin disable linode
docker plugin upgrade linode
docker plugin enable linode
```

**Comment by displague** [comment]
There's definitely something to be desired..

I created a swarm where the master node was given `test-vol` and it worked fine there.

The I attempted to send the volume to the worker and back.

```
$ docker run -it --rm --mount volume-driver=linode,source=test-vol,destination=/test,volume-opt=size=25 alpine
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/7d18c1aa418bbda64a97d55c89a1a6c14924145d34b6ee72e934f7cb8b200803/rootfs': VolumeDriver.Mount: EOF.

$ eval $(docker-machine env swarm-master01)

$ docker run -it --rm --mount volume-driver=linode,source=test-vol,destination=/test,volume-opt=size=25 alpine
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/6dfb5d2d267b38ea2d00df5eaf2b87335cce0e8f44c7dd2e54a56e703aa429f3/rootfs': VolumeDriver.Mount: Error mounting volume(/dev/disk/by-id/scsi-0Linode_Volume_test-vol) to directory(/mnt/test-vol): exit status 255.
```

**Pull request merged**
